---
title: "R course"
author: "Berry Boessenkool, <berry-b@gmx.de>"
site: bookdown::bookdown_site
documentclass: book
output:
  bookdown::gitbook:
    number_sections: false
    toc_depth: 1
    config:
      toc:
        toc_float:
          collapsed: true
editor_options: 
  chunk_output_type: console
---

# welcome {#welcome}

This website has been moved to [brry.github.io/course](https://brry.github.io/course/)

# install {#install}

This website has been moved to [brry.github.io/course](https://brry.github.io/course/install.html)

# settings {#settings}

This website has been moved to [brry.github.io/course](https://brry.github.io/course/settings.html)

# good practice {#good-practice}

This website has been moved to [brry.github.io/course](https://brry.github.io/course/good-practice.html)

# elegant code {#elegant-code}

This website has been moved to [brry.github.io/course](https://brry.github.io/course/elegant-code.html)

# packages {#packages}

This website has been moved to [brry.github.io/course](https://brry.github.io/course/packages.html)

# git {#git}

This website has been moved to [brry.github.io/course](https://brry.github.io/course/git.html)

# quarto {#quarto}

This website has been moved to [brry.github.io/course](https://brry.github.io/course/quarto.html)

# resources

This website has been moved to [brry.github.io/course](https://brry.github.io/course/resources.html)

# AI

This website has been moved to [brry.github.io/course](https://brry.github.io/course/ai.html)

# saveload

This website has been moved to [brry.github.io/course](https://brry.github.io/course/saveload.html)

# sumatra {#sumatra}

This website has been moved to [brry.github.io/course](https://brry.github.io/course/sumatra.html)

# project

This website has been moved to [brry.github.io/course](https://brry.github.io/course/project.html)

# VS Code

This website has been moved to [brry.github.io/course](https://brry.github.io/course/vs-code.html)

# installieren

Diese Website ist umgezogen zu [brry.github.io/course](https://brry.github.io/course/installieren.html)
